stages:
  - dep
  - test

before_script:
  - mkdir -p /go/src/github.com/martinomburajr /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/github.com/martinomburajr/algostructures
  - ln -s /go/src/github.com/martinomburajr /go/src/_/builds/martinomburajr
  - apk add --no-cache make build-base
  - make dep

dep:
  image: golang:alpine
  stage: dep
  script:
    - make dep

unit_tests:
  image: golang:alpine
  stage: test
  script:
    - make test

unit_test_data_race:
  image: golang:alpine
  stage: test
  script:
    - make race

